default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host:     <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: "e_wallet_development"
test:
  <<: *default
  database: "e_wallet_test"
production:
  <<: *default
  database: "e_wallet_production"
